import type { Metadata } from "next";
import Navbar from "./navbar";
import Header from "./header";
export const metadata: Metadata = {
    title: "MeetUp: All is one solution to online meets",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="w-full flex">
            <Navbar></Navbar>
            <div className="h-screen w-full relative overflow-y-auto">
                <Header></Header>
                <div className=" text-3 m-3 ">
                    {children}
                </div>
            </div>
        </main >


    );
}
