import type { Metadata } from "next";

import "./globals.css";
import "@stream-io/video-react-sdk/dist/css/styles.css";

import MenuProvider from "@/providers/menuProvider";
import ClerkProviderWrapper from "@/providers/clerkProvider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-1 w-full text-3`}>
        <ClerkProviderWrapper>
          <MenuProvider>
            {children}
            <Toaster />
          </MenuProvider>
        </ClerkProviderWrapper>
      </body>
    </html>
  );
}
