import type { Metadata } from "next";
import localFont from "next/font/local";

import { ClerkProvider } from "@clerk/nextjs";


import "./globals.css";
import MenuProvider from "@/hooks/use-menu";
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-1 w-full text-3`}
      >

        <ClerkProvider appearance={{
          // layout
          variables: {
            colorBackground: "#1C1F2E",
            colorInputText: "#fff",
            colorText: "#C9DDFF",
            colorInputBackground: "#161925",
            colorPrimary: "#0E78F9",
            colorNeutral: "#fff",
            colorTextSecondary: "#fff"
          }
        }}>
          <MenuProvider>
            {children}
            <Toaster />
          </MenuProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
